const NavActionTypes = {
  SET_SELECTED_NAV_BUTTON: "SET_SELECTED_NAV_BUTTON",
  TOGGLE_NAV_BUTTON_CLICKED: "TOGGLE_NAV_BUTTON_CLICKED",
  SET_SCROLL_TO_SECTION_FUNCTION: "SET_SCROLL_TO_SECTION_FUNCTION",
};

export default NavActionTypes;
